name: College Football News Aggregator

on:
  schedule:
    # Saturday at 11:00 PM UTC (adjust for your timezone)
    - cron: '0 23 * * 6'
    # Sunday at 9:00 AM UTC (adjust for your timezone)
    - cron: '0 9 * * 0'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  aggregate-news:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run news aggregator
      env:
        EMAIL_SMTP_SERVER: ${{ secrets.EMAIL_SMTP_SERVER }}
        EMAIL_SMTP_PORT: ${{ secrets.EMAIL_SMTP_PORT }}
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        LOG_LEVEL: INFO
      run: |
        python news_aggregator.py
    
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-logs
        path: |
          *.log
        retention-days: 7
